#pragma once
// evm.codes
#define STOP emit(0x00)
#define ADD emit(0x01)
#define MUL emit(0x02)
#define SUB emit(0x03)
#define DIV emit(0x04)
#define SDIV emit(0x05)
#define MOD emit(0x06)
#define SMOD emit(0x07)
#define ADDMOD emit(0x08)
#define MULMOD emit(0x09)
#define EXP emit(0x0a)
#define SIGNEXTEND emit(0x0b)

#define LT emit(0x10)
#define GT emit(0x11)
#define SLT emit(0x12)
#define SGT emit(0x13)
#define EQ emit(0x14)
#define ISZERO emit(0x15)
#define AND emit(0x16)
#define OR emit(0x17)
#define XOR emit(0x18)
#define NOT emit(0x19)
#define BYTE emit(0x1a)
#define SHL emit(0x1b)
#define SHR emit(0x1c)
#define SAR emit(0x1d)

#define SHA3 emit(0x20)

#define ADDRESS emit(0x30)
#define BALANCE emit(0x31)
#define ORIGIN emit(0x32)
#define CALLER emit(0x33)
#define CALLVALUE emit(0x34)
#define CALLDATALOAD emit(0x35)
#define CALLDATASIZE emit(0x36)
#define CALLDATACOPY emit(0x37)
#define CODESIZE emit(0x38)
#define CODECOPY emit(0x39)
#define GASPRICE emit(0x3a)
#define EXTCODESIZE emit(0x3b)
#define EXTCODECOPY emit(0x3c)
#define RETURNDATASIZE emit(0x3d)
#define RETURNDATACOPY emit(0x3e)
#define EXTCODEHASH emit(0x3f)

#define BLOCKHASH emit(0x40)
#define COINBASE emit(0x41)
#define TIMESTAMP emit(0x42)
#define BLOCKNUMBER emit(0x43)
#define DIFFICULTY emit(0x44)
#define PREVRANDAO emit(0x44)
#define GASLIMIT emit(0x45)
#define CHAINID emit(0x46)
#define SELFBALANCE emit(0x47)
#define BASEFEE emit(0x48)

#define POP emit(0x50)
#define MLOAD emit(0x51)
#define MSTORE emit(0x52)
#define MSTORE8 emit(0x53)
#define SLOAD emit(0x54)
#define SSTORE emit(0x55)
#define JUMP emit(0x56)
#define JUMPI emit(0x57)
#define PROGCNT emit(0x58)
#define MEMSIZE emit(0x59)
#define GASLEFT emit(0x5a)
#define JUMPDEST emit(0x5b)

#ifdef HAS_PUSH0
#define PUSH0 emit(0x5f)
#endif

#define LOG0 emit(0xa0)
#define LOG1 emit(0xa1)
#define LOG2 emit(0xa2)
#define LOG3 emit(0xa3)
#define LOG4 emit(0xa4)

#define CREATE emit(0xf0)
#define CALL emit(0xf1)
#define CALLCODE emit(0xf2)
#define RETURN emit(0xf3)
#define DELEGATECALL emit(0xf4)
#define CREATE2 emit(0xf5)
#define STATICCALL emit(0xfa)
#define REVERT emit(0xfd)
#define THROW emit(0xfe)
#define SELFDESTRUCT emit(0xff)

#include "push-dup-swap.h"
